In [2]:
import numpy as np

In [3]:
a=np.array(1)

In [4]:
a

array(1)

In [9]:
ndarr_1 = np.array([1,2,3])
print(ndarr_1)

[1 2 3]


In [11]:
ndarr_2=np.array([1,2.0,3])
print(ndarr_2)

[1. 2. 3.]


In [13]:
ndarr_3=np.array([1,2.0,'A'])
print(ndarr_3)

['1' '2.0' 'A']


In [28]:
#배열의 정보
#ndarray.dtype
print(ndarr_1.dtype)
print(ndarr_2.dtype)
print(ndarr_3.dtype)
      
print(np.array(1+2).dtype)
print(np.array(print).dtype)

int32
float64
<U32
int32
object


#자료형 저장

In [ ]:
dtype1=np.array([1,2,3],dtype=np.int8)
print(dtype1.dtype)

In [32]:
dtype2=np.array([1,2,3],dtype=float)
print(dtype2.dtype)

float64


In [34]:
dtype4=np.array([1,2.1,'3'],dtype=int)
print(dtype4)
print(dtype4.dtype)

[1 2 3]
int32


In [35]:
dtype5=np.array([1,'data','print'],dtype=float)
print(dtype5.dtype)

ValueError: could not convert string to float: 'data'

##배열의 정보 확인

In [37]:
print(ndarr_1.shape) #배열크기 확인

(3,)


In [38]:
print(ndarr_1.ndim)  ##배열차원 확인

1


In [39]:
vector=np.array([1,2,3])
print(vector)
print(vector.shape)
print(vector.ndim)
print(vector.dtype)

[1 2 3]
(3,)
1
int32


In [42]:
matrix=np.array([[1,2,3],[4,5,6]])
print(matrix)
print(matrix.shape)
print(matrix.ndim)
print(matrix.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
2
int32


In [44]:
tensor=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(tensor)
print(tensor.shape)
print(tensor.ndim)
print(tensor.dtype)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)
3
int32


In [47]:
print(vector.size)
print(matrix.size)
print(tensor.size)

3
6
12


In [57]:
matrix=np.array([[1,2,3],[2,4,6],[3,6,9]])
print(matrix)
print(matrix.shape)
print(matrix.ndim)
print(matrix.dtype)
print(matrix.size)

[[1 2 3]
 [2 4 6]
 [3 6 9]]
(3, 3)
2
int32
9


## 자료형 변환(리스트)

리스->ndarray 변환

In [59]:
list1=[1,2,3]
arr1=np.array(list1)
print(arr1)

[1 2 3]


In [62]:
arr2=np.array([1,2,3])
list2=list(arr2)
print(list2)

[1, 2, 3]


In [64]:
list3=[[1,2,3],[4,5,6]]
arr3=np.array(list3)
print(arr3)

[[1 2 3]
 [4 5 6]]


In [65]:
list4=[[1,2,3,4],[5,6,7]]
arr4=np.array(list4)
print(arr4)

[list([1, 2, 3, 4]) list([5, 6, 7])]


C:\Users\admin\AppData\Local\Temp\ipykernel_9972\2642677926.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr4=np.array(list4)


## 자료형 변환(리스트) -튜플

In [68]:
tuple1={1,2,3}
arr=np.array(tuple1)
print(tuple1)

{1, 2, 3}


In [69]:
arr=np.array({1,2,3})
tuple2=tuple(arr2)
print(tuple2)

(1, 2, 3)


## 자료형 변환(리스트) -세트,딕셔너리

In [74]:
set1={1,2,3}
arr=np.array(set1)
print(arr)
print(arr.size) #세트는 변환되지않음
print(arr.shape)

{1, 2, 3}
1
()


In [77]:
dict1={'a':1,'b':2,'c':3}
arr=np.array(dict1)
print(arr)
print(arr.size)

{'a': 1, 'b': 2, 'c': 3}


##배열 인덱싱
리스트 인덱싱과 유사

In [82]:
list0=[[[1,2],[3,4]],[[5,6],[7,8]]]
#1가져오기
print(list0[0][0][0])
#4가져오기
print(list0[0][1][1])
#7가져오기
print(list0[1][1][0])

1
4
7


In [84]:
arr0=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
#1가져오기
print(arr0[0][0][0])
#4가져오기
print(arr0[0][1][1])
#7가져오기
print(arr0[1][1][0])

1
4
7


ndarry의 인덱싱
-array[row,col]

In [90]:
arr_=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr_[0,0,0])
print(arr_[0,1,1])
print(arr_[1,1,0])

1
4
7


In [97]:
arr_1=np.array([[1,2],
                [3,4],
                [5,6]])
# 0행 가져와서 2차원 배열 만들기
print(arr_1[[0]])
# 0,2행 가져와서 2차원 배열 만들기
print(arr_1[[0,2]])
#다음답?
print(arr_1[[0,1,2],[0,1,0]])  #0,0 요소 1,1 요소 2,0
print(arr_1[[0,0],[1,1]])

[[1 2]]
[[1 2]
 [5 6]]
[1 4 5]
[2 2]


In [108]:
arr_2=np.array([[1,2,3],
              [4,5,6],
              [7,8,9],
              [10,11,12]])

#두개의 배열 만들기
b=np.array([0,1,2,3])
c=np.array([0,2,0,1])
#다음 코드실행결과
print(arr_2[b,c])

[ 1  6  7 11]


##Boolean 인덱싱

In [125]:
arr=np.array([1,2,3,4,5])
             
#True,False
print(arr[[True,False,True,True,False]])

[1 3 4]


In [122]:
score=np.array([[78,91,8,89,93,65],
                [82,87,96,79,91,73]])

print(score[0][score[0]>=90])
print(score[1][score[1]>=90])

[91 93]
[96 91]


## 배열 슬라이싱

In [5]:
matrix=np.array([[1,2,3,4,5],
               [6,7,8,9,10],
               [11,12,13,14,15],
               [16,17,18,19,20]])

In [10]:
print(matrix[:,0])
print(matrix[:,:1])

[ 1  6 11 16]
[[ 1]
 [ 6]
 [11]
 [16]]


In [13]:
print(matrix[1,:])  #1행 전체 슬라이싱  row,col :이면 전체를표시
print(matrix[1])   #rank>row>col순으로 콜론생략가능
print(matrix[1:2,:])

[ 6  7  8  9 10]
[ 6  7  8  9 10]
[[ 6  7  8  9 10]]


In [16]:
print(matrix[:,3:])
print(matrix[0,1:-1])  # 4=-1g하고 같은뜻임 뒤에서 부터니까

[[ 4  5]
 [ 9 10]
 [14 15]
 [19 20]]
[2 3 4]


In [20]:
print(matrix[-2:,-3:])
print(matrix[1:-1,1:3])

[[13 14 15]
 [18 19 20]]
[[ 7  8]
 [12 13]]


In [22]:
print(matrix[[1,3],2:])
print(matrix[1:-1,[1,3]])

[[ 8  9 10]
 [18 19 20]]
[[ 7  9]
 [12 14]]


In [25]:
tensor = np.array([[[1,2,3],[4,5,6]],
                   [[7,8,9],[10,11,12]]])

In [40]:
print(tensor[[1,0,0],[1,0,1],[0,1,2]])   ## 1,0,0 ,1,0,1, 0,1,2 하나씩 맞춤

[10  2  6]


In [41]:
tensor

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [44]:
print(tensor[0,:,0:2])
print(tensor[1,:,2])

[[1 2]
 [4 5]]
[ 9 12]
