## Reshape

배열의 shape을 변형해주는 함수

In [4]:
import numpy as np

In [8]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr.reshape(3,2))
print(arr.reshape(6,1))
print(arr.reshape(1,6))

[[1 2]
 [3 4]
 [5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
[[1 2 3 4 5 6]]


In [11]:
print(arr.reshape(3,1,2))

print(arr.reshape(-1,2))  ##?x2 배열로 변형 행을 모르겠는데, 열은2개로할때
print(arr.reshape(2,-1))  

[[[1 2]]

 [[3 4]]

 [[5 6]]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 3]
 [4 5 6]]


In [13]:
tensor=np.array(range(1,37)) ##3,3,4

In [16]:
print(tensor.reshape[3,3,4])

TypeError: 'builtin_function_or_method' object is not subscriptable

tensor 배열을 2차원 배열로 변형시켜봅시다. 열의 개수는 9개

In [17]:
tensor.reshpe

AttributeError: 'numpy.ndarray' object has no attribute 'reshpe'

##Flatten
다차원 배열 을 1차원배열로 변경

In [21]:
print(tensor.flatten())

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36]


## Arange

In [22]:
#np.arange(size)
print(np.arange(30))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


In [24]:
##np.arnage(start,end,step)
print(np.arange(0,10,2))

[0 2 4 6 8]


In [25]:
#Arange,Reshape같이

print(np.arange(1,26).reshape(5,5))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [26]:
print(np.arange(0,6,0.2).reshape(3,2,5))

[[[0.  0.2 0.4 0.6 0.8]
  [1.  1.2 1.4 1.6 1.8]]

 [[2.  2.2 2.4 2.6 2.8]
  [3.  3.2 3.4 3.6 3.8]]

 [[4.  4.2 4.4 4.6 4.8]
  [5.  5.2 5.4 5.6 5.8]]]


In [33]:
print(np.arange(100,191,10).reshape(2,5))

[[100 110 120 130 140]
 [150 160 170 180 190]]


In [40]:
print(np.arange(-2,2.1,0.5).reshape(1,3,3))

[[[-2.  -1.5 -1. ]
  [-0.5  0.   0.5]
  [ 1.   1.5  2. ]]]


# Zeros
# 0으로 채워진 배열 생성

In [48]:
print(np.zeros(shape=(5,),dtype=np.int8))

[0 0 0 0 0]


In [49]:
print(np.zeros((2,3)))

[[0. 0. 0.]
 [0. 0. 0.]]


In [50]:
##Ones 는 1로 채워짐 zeros와 같음,
#empty함수는 비어있는 배열생성 값을주지않음


##Zeros_like/Ones_like//Empty_like
입력받은 배열과 같은 shape,dtype의 배열생성

In [52]:
matrix=np.arange(24).reshape(4,6)
print(np.zeros_like(matrix))

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [54]:
matrix=np.arange(30).reshape(5,6)
print(np.empty_like(matrix))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


In [55]:
## Identity 단위행렬 대각선이 1이고 나머지가 0인 정사각형행렬


In [56]:
print(np.identity(5,dtype=np.int8))

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [57]:
print(np.identity(2))

[[1. 0.]
 [0. 1.]]


In [59]:
##Eye
#대각선이 1로 채워지는 행렬
#대각선의 시작 위치 지정가능 
#np.eye(size,M,K,dtype)
print(np.eye(5,dtype=np.int8))

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [61]:
print(np.eye(5,M=10,k=1))

[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]]


In [65]:
##FULL
##입력값으로 채움
##np.full(shape),value)
print(np.full((2,5),5))

[[5 5 5 5 5]
 [5 5 5 5 5]]


In [68]:
##Random.randint
#np.random.randint(range)
##0~5까지 정수중하나뽑기
print(np.random.randint(6))
#1~19까지의 정수뽑기
print(np.random.randint(1,20,2))

5
[ 9 11]


In [70]:
#Random.rand
#랜덤한 값으로 채워지는 배열
#0~1사이의 값을 가짐
#np.random.rand(shape)
print(np.random.rand(3))

[0.90791078 0.42814884 0.73269556]


In [72]:
print(np.random.randn(3))  ##- 임..

[0.66748804 0.53513545 0.81843303]


In [73]:
#sum
matrix =np.arange(1,7).reshape(2,3)
print(matrix)

[[1 2 3]
 [4 5 6]]


In [74]:
matrix.sum()

21

In [77]:
print(matrix.sum(axis=0))## 열 합
print(matrix.sum(axis=1))## 행 합

[5 7 9]
[ 6 15]


In [79]:
##평균
#print(matrix,mean())
print(matrix.mean(axis=0)) ##행 끼리 평균
print(matrix.mean(axis=1)) ##열 끼리 평균


[2.5 3.5 4.5]
[2. 5.]


In [81]:
##표준편차 (std)
print(matrix.std())
print(matrix.std(axis=0)) 
print(matrix.std(axis=1)) 

1.707825127659933
[1.5 1.5 1.5]
[0.81649658 0.81649658]


In [84]:
## sort
#배열으 순선대로 정렬
#1~100 숫자 중 5개를 뽑아 배열생성
vector=np.array([np.random.randint(1,100)
               for n in range(5)])
print(vector)

[66 91  4 15 28]


In [89]:
print(np.sort(vector))
print(np.sort(vector)[::-1])  #리버스

[ 4 15 28 66 91]
[91 66 28 15  4]


In [102]:
matrix=np.array(np.random.randint(1,100)
                for n in range(20)),reshape[4,5]

print(matrix)

NameError: name 'reshape' is not defined

In [105]:
##Vstack 배열합치기
#2개이상의 배열을 수직으로 합체
#np.vstack([arr1,arr2])
vector1=np.array([1,2,3])
vector2=np.array([4,5,6])
print(np.vstack([vector1,vector2]))

[[1 2 3]
 [4 5 6]]


In [108]:
##Hstack 배열합치기
#2개이상의 배열을 수평으로 합체
#np.hstack([arr1,arr2])
vector1=np.array([1,2,3]).reshape(3,1)
vector2=np.array([4,5,6]).reshape(3,1)
print(np.hstack([vector1,vector2]))

[[1 4]
 [2 5]
 [3 6]]


In [115]:
##배열 합치기 Concatenate
#2개이상의 배열을 수직,수평합치기

vector1=np.array([1,2,3])
vector2=np.array([4,5,6])
print(np.concatenate([vector1,vector2],axis=0)) #1은 안됨

[1 2 3]


In [119]:
v1=np.arange(1,5).reshape(2,2)
v2=np.arange(5,9).reshape(2,2)
print(np.concatenate([v1,v2],axis=1))

[[1 2 5 6]
 [3 4 7 8]]


In [142]:
##행과열 바꾸기 traspose
#matrix3=np.array([5,6])
#ndarray.T
matrix3=np.array([[5,6]])
print(matrix3)

[[5 6]]


In [143]:
print(matrix3.T)

[[5]
 [6]]


In [147]:
## 인데스 반환 함수
a= np.arange(1,11).reshape(2,5)
print(a)
print(np.argmax(a),np.argmin(a))  ##a,aix=0

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
9 0


## 배열 인덱싱 (Fancy index)

In [153]:
a=np.arange(1,11)
b=np.array([3,4,5,6])
print(a)
print(b)
print(a[b])

[ 1  2  3  4  5  6  7  8  9 10]
[3 4 5 6]
[4 5 6 7]


In [155]:
a=np.arange(10,20)
b=np.argmax(a)
print(a)
print(b)
print(a[b])

[10 11 12 13 14 15 16 17 18 19]
9
19
