In [1]:
import numpy as np

## Numpy 배열연산

### shape

In [6]:
arr1=np.arange(1,7,dtype=np.float32).reshape(2,3)
arr2=np.arange(11,17,dtype=np.int32).reshape(2,3)
print(arr1+arr2)

[[12. 14. 16.]
 [18. 20. 22.]]


In [7]:
## +,/,**,//,%%

In [8]:
##연산함수
#np.add(arr1,arr2),np.subtract(arr1,arr2)  np.multply(arr1,arr2) np.divide(arr1,arr2)

In [9]:
#Broadcastig 연산하고자하는 배열의 모양이 다를경우 연산하고잘할때

In [10]:
arr3=np.arange(10).reshape(5,2)
arr4=np.arange(10).reshape(2,5)
print(arr3+arr4)

ValueError: operands could not be broadcast together with shapes (5,2) (2,5) 

In [13]:
Scalar= 10
vector=np.array([1,2,3])
print(Scalar+vector)      #자동으로 브로드캐스팅적용

[11 12 13]


In [14]:
matrix=np.arange(1,10).reshape(3,3)
vector=np.arange(11,14).reshape(1,3)
print(matrix+vector)

[[12 14 16]
 [15 17 19]
 [18 20 22]]


In [19]:
arr1=np.array([1,2,3])
arr2=np.array([1,2,3]).reshape(3,1)
print(arr1)
print(arr2)
print(arr1+arr2)  ## 1,2,3-1,2,3-1,2,3, 1,1,1-2,2,2-3,3,3

[1 2 3]
[[1]
 [2]
 [3]]
[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [23]:
#행렬 연산
#np.dot(arr1,arr2)
arr2=np.array([1,2,3]).T
print(np.dot(arr1,arr2))

14


In [24]:
np.dot(arr1,arr2)
arr1.dot(arr2)
arr1@arr2

14