# #Numpy 파이 입출력

In [5]:
#파일 처리  
import numpy as np

In [19]:
n=np.random.randn(3,5)
print(n)

[[-0.75530602 -1.76040272 -0.9591362  -0.30372962 -0.33915386]
 [ 0.78107439  1.85857521 -1.08372596 -1.32320633 -2.30719225]
 [-0.0082877   0.58867419 -1.60158639 -0.09789727  0.46701784]]


In [20]:
n.tofile('n.npy')  #파일저장

In [24]:
m=np.fromfile('n.npy')
print(m)

[-0.75530602 -1.76040272 -0.9591362  -0.30372962 -0.33915386  0.78107439
  1.85857521 -1.08372596 -1.32320633 -2.30719225 -0.0082877   0.58867419
 -1.60158639 -0.09789727  0.46701784]


In [25]:
np.fromfile('C:\STUDY\StudyPython22\jupyter/n.npy').reshape(3,5)  ##shape(3,5)
print(m)

[-0.75530602 -1.76040272 -0.9591362  -0.30372962 -0.33915386  0.78107439
  1.85857521 -1.08372596 -1.32320633 -2.30719225 -0.0082877   0.58867419
 -1.60158639 -0.09789727  0.46701784]


In [23]:
np.save('n1.npy',n)
m1=np.load('n1.npy')
print(m1) #위아래 저장방식이달라서 방식에따라 불러오기

[[-0.75530602 -1.76040272 -0.9591362  -0.30372962 -0.33915386]
 [ 0.78107439  1.85857521 -1.08372596 -1.32320633 -2.30719225]
 [-0.0082877   0.58867419 -1.60158639 -0.09789727  0.46701784]]
