# #Numpy 파이 입출력

In [2]:
#파일 처리  
import numpy as np

In [3]:
n=np.random.randn(3,5)
print(n)

[[-1.82427657  0.45289522 -1.57902754  0.12535716 -1.05139542]
 [-0.05325916  1.24069104 -0.96705165  1.15786539  1.01592131]
 [ 1.57069902  0.277656   -1.40398437  0.08415142  0.15779156]]


In [4]:
n.tofile('n.npy')  #파일저장

In [5]:
m=np.fromfile('n.npy')
print(m)

[-1.82427657  0.45289522 -1.57902754  0.12535716 -1.05139542 -0.05325916
  1.24069104 -0.96705165  1.15786539  1.01592131  1.57069902  0.277656
 -1.40398437  0.08415142  0.15779156]


In [6]:
np.fromfile('C:\STUDY\StudyPython22\jupyter/n.npy').reshape(3,5)  ##shape(3,5)
print(m)

[-1.82427657  0.45289522 -1.57902754  0.12535716 -1.05139542 -0.05325916
  1.24069104 -0.96705165  1.15786539  1.01592131  1.57069902  0.277656
 -1.40398437  0.08415142  0.15779156]


In [7]:
#np.save('n1.npy',n)
m1=np.load('n1.npy')
print(m1) #위아래 저장방식이달라서 방식에따라 불러오기

[[-0.75530602 -1.76040272 -0.9591362  -0.30372962 -0.33915386]
 [ 0.78107439  1.85857521 -1.08372596 -1.32320633 -2.30719225]
 [-0.0082877   0.58867419 -1.60158639 -0.09789727  0.46701784]]


In [9]:
##txt 파일 저장 (np.svetxt)
#np.savetxt('n.txt',n)
np.savetxt('n.txt',n)

In [10]:
#txt 파일 불러보기
np.loadtxt('n.txt')

array([[-1.82427657,  0.45289522, -1.57902754,  0.12535716, -1.05139542],
       [-0.05325916,  1.24069104, -0.96705165,  1.15786539,  1.01592131],
       [ 1.57069902,  0.277656  , -1.40398437,  0.08415142,  0.15779156]])

In [11]:
#csv 파일 저장,불러오기
#np.savetxt('n.csv',n) 확장자만 csv인데 ,로 구분
#np.loadtxt('n.csv')

In [13]:
np.savetxt('n.csv',n,delimiter=',')

In [15]:
np.loadtxt('n.csv',delimiter=',')

array([[-1.82427657,  0.45289522, -1.57902754,  0.12535716, -1.05139542],
       [-0.05325916,  1.24069104, -0.96705165,  1.15786539,  1.01592131],
       [ 1.57069902,  0.277656  , -1.40398437,  0.08415142,  0.15779156]])

In [16]:
import numpy as np

In [26]:
matrix=np.arange(1,26).reshape(5,5)
matrix
np.savetxt('data.csv',matrix,delimiter=',')

In [28]:
np.loadtxt('data.csv',delimiter=',',dtype=np.int8)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]], dtype=int8)

In [38]:
arr1=np.loadtxt('./data/06_data1.txt',dtype=np.str_)
print(arr1)

[['1' '15' '14' '4']
 ['12' '6' '7' '9']
 ['8' '10' '11' '5']
 ['13' '3' '2' '16']]


In [40]:
np.loadtxt('./data/06_data1.txt',delimiter='\t',dtype=np.str_)

array([['1', '15', '14', '4'],
       ['12', '6', '7', '9'],
       ['8', '10', '11', '5'],
       ['13', '3', '2', '16']], dtype='<U2')

In [45]:
arr2=np.loadtxt('./data/06_data2.txt',delimiter= ',',dtype=str)
print(arr2)

[['1' '15' '14' '4']
 ['12' '6' '7' '9']
 ['8' '10' '11' '5']
 ['13' '3' '2' '16']]


In [48]:
data=np.loadtxt('./data/ex1_지역별전기요금.csv',delimiter=',',dtype=np.int64)
print(data[:5,:])

[[      1  565082     273   27177]
 [      2 2827233     444   45111]
 [      3 1144913     289   29043]
 [      4 1131034     230   22436]
 [      5  380425     391   38020]]


In [54]:
print(data.shape)
#중복지역확인
print(np.unique(data[:,0]))

(17, 4)
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]


In [97]:
#데이터 크기순 정렬(argsort 사용)  ##0부터시작으로 그래서 9가 제일작음 오름차순으로 하고 1열기준으로 작은순부터
print(data[:,1].argsort())

[ 9 14 10  4  6  0 16 13  5 12 11 15  7  3  2  8  1]


In [56]:
#fancy index  2차원에서는 사용안하는것이 좋다
print(data[data[:,1].argsort()])

[[     10   49394     580   57091]
 [     15  258605     221   22180]
 [     11  323151     353   35470]
 [      5  380425     391   38020]
 [      7  425659     344   32331]
 [      1  565082     273   27177]
 [     17  584500     268   26899]
 [     14  634696     285   28556]
 [      6  668623     364   35245]
 [     13  726699     249   25120]
 [     12  734723     398   40049]
 [     16  742285     282   27901]
 [      8  947300     366   36274]
 [      4 1131034     230   22436]
 [      3 1144913     289   29043]
 [      9 2737725     361   36569]
 [      2 2827233     444   45111]]


In [68]:
#데이터 통걔
#저눅 대상 가구수의 합
print(np.sum(data[:,1]))  ##data[:,1].sum()
#가구당 평균전력 사용량의 평균값
print(round(data[:,2].mean(),2))  ##round 소수점 함수

14882047
335.18


In [76]:
e_sum=np.sum(data[:,2])
e_sum
n_rows = data.shape[0]
n_rows

round(e_sum/n_rows,2)

335.18

In [79]:
###가구당 평균 전력 사용량이 평균이상인 지역과 대상 가구수 추출  0지역,2대상가가수만 가져오니까 0:2
avg_=data[:,2].mean()
print(data[data[:,2]>avg_,0:2])

[[      2 2827233]
 [      5  380425]
 [      6  668623]
 [      7  425659]
 [      8  947300]
 [      9 2737725]
 [     10   49394]
 [     11  323151]
 [     12  734723]]


In [96]:
data2=np.loadtxt('./data/ex2_전년대비_시도별_교통사망사고.csv',delimiter=',',dtype=str)
print(data2)

[['2014' '1' '218' '4.8' '-9' '-4']
 ['2014' '2' '872' '19' '-45' '-4.9']
 ['2014' '3' '401' '8.7' '-45' '-10.1']
 ['2014' '4' '464' '10.1' '-41' '-8.1']
 ['2014' '5' '99' '2.2' '-5' '-4.8']
 ['2014' '6' '182' '4' '19' '11.7']
 ['2014' '7' '99' '2.2' '8' '8.8']
 ['2014' '8' '163' '3.6' '-47' '-22.4']
 ['2014' '9' '386' '8.4' '14' '3.8']
 ['2014' '10' '20' '0.4' '0' '0']
 ['2014' '11' '103' '2.2' '-16' '-13.4']
 ['2014' '12' '144' '3.1' '-6' '-4']
 ['2014' '13' '400' '8.7' '-35' '-8']
 ['2014' '14' '317' '6.9' '-35' '-9.9']
 ['2014' '15' '86' '1.9' '-14' '-14']
 ['2014' '16' '387' '8.4' '-5' '-1.3']
 ['2014' '17' '242' '5.3' '-31' '-11.4']]
