In [2]:
import numpy as np

# [문제1] 위 파일을 읽어보고 상위 3개의 (발생년도, 발생건수, 구성비)의 데이터를 추출해 봅시다.

In [67]:
data2=np.loadtxt('./data/ex2_전년대비_시도별_교통사망사고.csv',delimiter=',',dtype=float)
print(data2)

[[ 2.014e+03  1.000e+00  2.180e+02  4.800e+00 -9.000e+00 -4.000e+00]
 [ 2.014e+03  2.000e+00  8.720e+02  1.900e+01 -4.500e+01 -4.900e+00]
 [ 2.014e+03  3.000e+00  4.010e+02  8.700e+00 -4.500e+01 -1.010e+01]
 [ 2.014e+03  4.000e+00  4.640e+02  1.010e+01 -4.100e+01 -8.100e+00]
 [ 2.014e+03  5.000e+00  9.900e+01  2.200e+00 -5.000e+00 -4.800e+00]
 [ 2.014e+03  6.000e+00  1.820e+02  4.000e+00  1.900e+01  1.170e+01]
 [ 2.014e+03  7.000e+00  9.900e+01  2.200e+00  8.000e+00  8.800e+00]
 [ 2.014e+03  8.000e+00  1.630e+02  3.600e+00 -4.700e+01 -2.240e+01]
 [ 2.014e+03  9.000e+00  3.860e+02  8.400e+00  1.400e+01  3.800e+00]
 [ 2.014e+03  1.000e+01  2.000e+01  4.000e-01  0.000e+00  0.000e+00]
 [ 2.014e+03  1.100e+01  1.030e+02  2.200e+00 -1.600e+01 -1.340e+01]
 [ 2.014e+03  1.200e+01  1.440e+02  3.100e+00 -6.000e+00 -4.000e+00]
 [ 2.014e+03  1.300e+01  4.000e+02  8.700e+00 -3.500e+01 -8.000e+00]
 [ 2.014e+03  1.400e+01  3.170e+02  6.900e+00 -3.500e+01 -9.900e+00]
 [ 2.014e+03  1.500e+01  8.600e+01

In [64]:
print(data2[:3,[0,2,3]])

[[2014.   218.     4.8]
 [2014.   872.    19. ]
 [2014.   401.     8.7]]


# [문제2] 위 데이터에서 부산에서 발생한 교통사망사고 모든 현황을 추출해 봅시다.

In [68]:
print(data2[7,:])

[2014.     8.   163.     3.6  -47.   -22.4]


# [문제3] 위 데이터에서 전국 사고 발생건수의 합계와 전국 평균을 계산해 봅시다.

In [37]:
d_sum=data2[:,2].sum()
print(d_sum)
d_mean=data2[:,2].mean()
print(round(d_mean,2))

4583
269.59


# [문제4] 위 데이터에서 교통사고 증감수가 가장 큰 지역의 모든 현황을 추출해 봅시다.

In [70]:
max(data2[:,4])

19.0

In [78]:
print(data2[data2[:,4]==max(data2[:,4])])

[[2014.     6.   182.     4.    19.    11.7]]


In [53]:
print(data2[:,4].argsort()[::-1])
print(data2[data2[:,4].argsort()][::-1])

[ 5  8  6  9  4 15 11  0 14 10 16 12 13  3  2  1  7]
[[2014    6  182    4   19   11]
 [2014    9  386    8   14    3]
 [2014    7   99    2    8    8]
 [2014   10   20    0    0    0]
 [2014    5   99    2   -5   -4]
 [2014   16  387    8   -5   -1]
 [2014   12  144    3   -6   -4]
 [2014    1  218    4   -9   -4]
 [2014   15   86    1  -14  -14]
 [2014   11  103    2  -16  -13]
 [2014   17  242    5  -31  -11]
 [2014   13  400    8  -35   -8]
 [2014   14  317    6  -35   -9]
 [2014    4  464   10  -41   -8]
 [2014    3  401    8  -45  -10]
 [2014    2  872   19  -45   -4]
 [2014    8  163    3  -47  -22]]


In [52]:
print(data2[5,:])

[2014    6  182    4   19   11]


# [문제5] 위 데이터에서 교통사고 증감률이 가장 작은 지역의 모든 현황을 추출해 봅시다.

In [79]:
min(data2[:,5])

-22.4

In [80]:
print(data2[data2[:,5]==min(data2[:,5])])

[[2014.     8.   163.     3.6  -47.   -22.4]]


In [54]:
print(data2[:,5].argsort())
print(data2[data2[:,5].argsort()])

[ 7 14 10 16  2 13  3 12 11  0  4  1 15  9  8  6  5]
[[2014    8  163    3  -47  -22]
 [2014   15   86    1  -14  -14]
 [2014   11  103    2  -16  -13]
 [2014   17  242    5  -31  -11]
 [2014    3  401    8  -45  -10]
 [2014   14  317    6  -35   -9]
 [2014    4  464   10  -41   -8]
 [2014   13  400    8  -35   -8]
 [2014   12  144    3   -6   -4]
 [2014    1  218    4   -9   -4]
 [2014    5   99    2   -5   -4]
 [2014    2  872   19  -45   -4]
 [2014   16  387    8   -5   -1]
 [2014   10   20    0    0    0]
 [2014    9  386    8   14    3]
 [2014    7   99    2    8    8]
 [2014    6  182    4   19   11]]


In [62]:
print(data2[data2[:,5]==0])

[[2014   10   20    0    0    0]]


# [문제6] 위 데이터에서 사고 발생 건수가 400건 이상인 곳의 지역과 교통사고 발생건수, 증감수, 증감률을 추출해 봅시다.

In [55]:
print(data2[:,2].argsort())
print(data2[data2[:,2].argsort()])

[ 9 14  4  6 10 11  7  5  0 16 13  8 15 12  2  3  1]
[[2014   10   20    0    0    0]
 [2014   15   86    1  -14  -14]
 [2014    5   99    2   -5   -4]
 [2014    7   99    2    8    8]
 [2014   11  103    2  -16  -13]
 [2014   12  144    3   -6   -4]
 [2014    8  163    3  -47  -22]
 [2014    6  182    4   19   11]
 [2014    1  218    4   -9   -4]
 [2014   17  242    5  -31  -11]
 [2014   14  317    6  -35   -9]
 [2014    9  386    8   14    3]
 [2014   16  387    8   -5   -1]
 [2014   13  400    8  -35   -8]
 [2014    3  401    8  -45  -10]
 [2014    4  464   10  -41   -8]
 [2014    2  872   19  -45   -4]]


In [57]:
print(data2[data2[:,2]>=400][:,[1,2,4,5]])

[[  2 872 -45  -4]
 [  3 401 -45 -10]
 [  4 464 -41  -8]
 [ 13 400 -35  -8]]
